# Generated by Django 5.2 on 2025-04-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_maintenancebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancebanner',
            name='message',
        ),
    ]
